[tool.poetry]
name = "py-music-player"
version = "0.5.1"
description = "A simple desktop music player with playlist and repeat functionality."
authors = "anonymByte-404"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11.9"
pygame = "^2.6.1"
tkinter = "*"
