[tool.poetry]
name = "py-music-player"
version = "1.8.8"
description = "A simple desktop music player with playlist and repeat functionality."
author = "anonymByte-404"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11.9"
pygame = "^2.6.1"
tkinterdnd2 = "^0.4.2"
mutagen = "^1.47.0"
